modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "recipedumper"
version = "${version}"
displayName = "RecipeDumper"
authors = "RedstoneWizard08"
description = '''
A simple utility for dumping recipes and tags.
'''
#logoFile = ""

[[dependencies.recipedumper]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recipedumper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recipedumper]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "BOTH"