modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"

[[mods]]
modId = "recipedumper"
version = "${file.jarVersion}"
displayName = "RecipeDumper"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/"
#logoFile="RecipeDumper.png"
#credits="Thanks for this example mod goes to Java"
#authors="Love, Cheese and small house plants"
description = '''

'''

[[dependencies.recipedumper]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recipedumper]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,1.20)"
ordering = "NONE"
side = "BOTH"
